spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 1qaz@WSX3edc
    url: jdbc:mysql://gz-cdb-lchxvw7f.sql.tencentcdb.com:63867/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
server:
  port: 8080
  compression:
    enabled: true